# Generated by Django 2.1.3 on 2018-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181114_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place_location_zip',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
